import type { JurySession, StudentRecord } from "@/types/session";
import { appName } from "@/lib/brand";
import { fmt } from "@/lib/timeFormat";

type Props = {
  session: JurySession;
  record: StudentRecord;
};

export default function StudentReportPrintable({ session, record }: Props) {
  const meta = `${session.jury_type} · ${session.department} · ${session.section} · Sem ${session.semester} · ${session.academic_year}`;

  return (
    <div
      style={{
        width: "800px",
        padding: "40px",
        background: "#ffffff",
        color: "#0f172a",
        fontFamily:
          '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
      }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
        <div>
          <div style={{ fontSize: 11, letterSpacing: 2, color: "#64748b", textTransform: "uppercase" }}>
            Jury Report
          </div>
          <div style={{ fontSize: 28, fontWeight: 700, marginTop: 6 }}>{record.student_name}</div>
          <div style={{ fontSize: 13, color: "#475569", marginTop: 4 }}>{meta}</div>
        </div>
        <div style={{ textAlign: "right", fontSize: 12, color: "#475569" }}>
          <div>
            Student #{record.student_order} of {session.number_of_students}
          </div>
          <div>{new Date(record.created_at).toLocaleString()}</div>
        </div>
      </div>

      <div
        style={{
          marginTop: 28,
          display: "grid",
          gridTemplateColumns: "repeat(4, 1fr)",
          gap: 12,
        }}
      >
        <Stat label="Total Used" value={fmt(record.total_time_used_seconds)} />
        <Stat label="Setup" value={fmt(record.setup_seconds)} />
        <Stat label="Presentation" value={fmt(record.presentation_seconds)} />
        <Stat
          label={record.overtime_seconds > 0 ? "Overtime" : "Time Saved"}
          value={
            record.overtime_seconds > 0
              ? `+${fmt(record.overtime_seconds)}`
              : fmt(record.time_saved_seconds)
          }
          tone={record.overtime_seconds > 0 ? "red" : "green"}
        />
      </div>

      <Section title="Timeline">
        <TsRow label="Setup started" value={formatTs(record.setup_started_at)} />
        <TsRow label="Presentation started" value={formatTs(record.presentation_started_at)} />
        <TsRow label="Ended" value={formatTs(record.ended_at)} />
      </Section>

      <Section title="Subject structure">
        <div style={{ fontSize: 13, color: "#334155" }}>
          {session.subjects.map((subject, index) => (
            <span key={index}>
              {index + 1}. {subject}
              {index < session.subjects.length - 1 ? "  ·  " : ""}
            </span>
          ))}
        </div>
        <div style={{ fontSize: 12, color: "#64748b", marginTop: 6 }}>
          {session.subjects.length} subjects × {fmt(session.per_subject_seconds)} + final feedback{" "}
          {fmt(session.feedback_seconds)}
        </div>
      </Section>

      <Section title="Final feedback">
        <div style={{ whiteSpace: "pre-wrap", fontSize: 13, color: "#0f172a", lineHeight: 1.55 }}>
          {record.feedback?.final || "-"}
        </div>
      </Section>

      {record.feedback?.perSubject && Object.keys(record.feedback.perSubject).length > 0 && (
        <Section title="Per-subject notes">
          <div style={{ display: "grid", gap: 10 }}>
            {Object.entries(record.feedback.perSubject).map(([subject, note]) => (
              <div
                key={subject}
                style={{ background: "#f8fafc", borderRadius: 10, padding: "10px 12px" }}
              >
                <div style={{ fontSize: 12, fontWeight: 600, color: "#334155" }}>{subject}</div>
                <div style={{ fontSize: 13, color: "#0f172a", marginTop: 2, whiteSpace: "pre-wrap" }}>
                  {note}
                </div>
              </div>
            ))}
          </div>
        </Section>
      )}

      <div
        style={{
          marginTop: 40,
          borderTop: "1px solid #e2e8f0",
          paddingTop: 12,
          fontSize: 11,
          color: "#94a3b8",
        }}
      >
        Generated by {appName}
      </div>
    </div>
  );
}

function Stat({ label, value, tone }: { label: string; value: string; tone?: "red" | "green" }) {
  const color = tone === "red" ? "#b91c1c" : tone === "green" ? "#047857" : "#0f172a";

  return (
    <div style={{ background: "#f8fafc", borderRadius: 12, padding: "12px 14px" }}>
      <div style={{ fontSize: 10, letterSpacing: 1.5, textTransform: "uppercase", color: "#64748b" }}>
        {label}
      </div>
      <div style={{ fontSize: 20, fontWeight: 700, color, marginTop: 4, fontVariantNumeric: "tabular-nums" }}>
        {value}
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginTop: 24 }}>
      <div style={{ fontSize: 10, letterSpacing: 2, textTransform: "uppercase", color: "#64748b" }}>
        {title}
      </div>
      <div style={{ marginTop: 8 }}>{children}</div>
    </div>
  );
}

function TsRow({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ display: "flex", justifyContent: "space-between", fontSize: 13, padding: "2px 0" }}>
      <span style={{ color: "#64748b" }}>{label}</span>
      <span style={{ color: "#0f172a", fontVariantNumeric: "tabular-nums" }}>{value}</span>
    </div>
  );
}

function formatTs(iso: string | null): string {
  if (!iso) return "-";
  return new Date(iso).toLocaleString();
}
